# Generated by Django 4.1.5 on 2023-02-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytclient',
            name='subscription',
        ),
        migrations.AddField(
            model_name='channel',
            name='subscription',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
