# Generated by Django 4.1.5 on 2023-02-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0002_remove_ytclient_subscription_channel_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
    ]
