# Generated by Django 4.1.5 on 2023-02-06 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_comment_ytvideo_remove_client_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalItemsOrder', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Cancelled'), (1, 'Placed'), (2, 'Shipped'), (3, 'Delivered')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ytvideo',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='emailID',
        ),
        migrations.RemoveField(
            model_name='client',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('CH', 'Windsor'), ('TO', 'Toronto'), ('CH', 'Chatham'), ('WL', 'WATERLOO')], default='WD', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='YTVideo',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='clientServing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='myapp1.client'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='itemServing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp1.type'),
        ),
        migrations.AddField(
            model_name='client',
            name='interested_in',
            field=models.ManyToManyField(to='myapp1.type'),
        ),
    ]
