# Generated by Django 4.1.5 on 2023-02-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_item_orderitem_type_remove_ytvideo_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='clientServing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='myapp1.client'),
        ),
    ]
