# Generated by Django 4.1.5 on 2023-02-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_orderitem_clientserving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='clientServing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='myapp1.client'),
        ),
    ]
